export let products = [
  {
    id: 1,
    title: "Casco Nolan n-80",
    price: 7500,
    stock: 5,
    description: "Casco integral nolan n-08",
    category: "helmets",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916329/supercuauh/nolan-n-80.jpg",
    rank: 5,
  },
  {
    id: 2,
    title: "Casco Scorpion AT-950",
    price: 12000,
    stock: 10,
    description: "Casco Scorpion AT-950, snow version with pinlock",
    category: "helmets",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916480/supercuauh/scorpion.jpg",
    rank: 4,
  },
  {
    id: 3,
    title: "Fox Gloves",
    price: 1200,
    stock: 5,
    description: "Fox Gloves motorcycle leather brown",
    category: "gloves",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916674/supercuauh/fox.jpg",
    rank: 3,
  },
  {
    id: 4,
    title: "YOMYM Guantes",
    price: 2500,
    stock: 5,
    description:
      "Tácticos para Hombres Mujer, Dedo Completo Nudillo Duro Guantes Tácticos Militares para Ciclismo, Motocicleta, Escalada, Senderismo, Equitación",
    category: "gloves",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916746/supercuauh/YOMYM.jpg",
    rank: 2.5,
  },
  {
    id: 5,
    title: "Magna Jacket",
    price: 10000,
    stock: 2,
    description:
      "Motorcycle Jacket for Men and Women Scorpion with Cordura Fabric for Enduro Motorbike Riding and Armor Foam Padding for Impact Protection, Dual Sport Motorcycle Jacket - Orange, Medium",
    category: "jackets",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916789/supercuauh/magna.jpg",
    rank: 4.5,
  },
  {
    id: 6,
    title: "JYG Motorcycle Jacket",
    price: 8200,
    stock: 7,
    description:
      "JYG Motorcycle Jacket for Men Casual Faux Leather Bomber Jacket with Removable Hood",
    category: "jackets",
    img: "https://res.cloudinary.com/duyywqqh3/image/upload/v1687916903/supercuauh/JYG.jpg",
    rank: 3.5,
  },
];
